version: '3.8'

services:
  
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - ${DB_PORT}:3306
    volumes:
      - my-db:/opt/volumes/db

volumes:
  my-db:
